name: Terraform Apply Base

on:
  workflow_call:
    inputs:
      # environment:
      #   required: true
      #   type: string
      role:
        required: true
        type: string
jobs:
  terraform-apply:
    name: TEST
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: test
        run: echo role "arn:aws:iam::${{ inputs.role }}:role/ecr-github-actions"