name: Plan
on: push
jobs:
  plan:
    strategy:
      matrix:
        environment: [staging, production]
    uses: plan: ./.github/workflows/terraform-plan-base.yml
    with:
      environment: ${{ matrix.environment }}
