name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - run: echo "test ${{inputs.environment}}"
      - run: echo "var is ${{vars.CAN_DEPLOY}}"
