name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
        contents: read
        pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "test ${{inputs.environment}}"