name: Terraform Apply

on: push

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write
    steps:
      - name: Check plan status
        id: check-plan-status
        run: |
          status="finished"

          if [[ "$status" == "errored" ]]; then
            exit 1
          else
            exit 0
          fi
