
name: "Test"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test"
        type: environment
        required: true

jobs:
  variables:
    name: Test ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    steps:
      - name: Test variables
        run: |
          echo "VARIABLE IS ${{var.VARIABLE}}"
          if [ -n "${{secrets.SECRET}}" ]; then
            echo "SECRET EXISTS"
          else
            echo "SECRET is not set"
          fi
          if [ -n "${{secrets.SECRET2}}" ]; then
            echo "SECRET2 EXISTS"
          else
            echo "SECRET2 is not set"
          fi