
name: "Test"
on:
  # This will trigger deployment to `development` on each push to main
  # `development` is set as a default environment below
  push:
    branches:
      - main
  # However, deployemnt to other environments (or re-running job for `development`) should be done manually
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true


jobs:
  variables:
    env:
      # If the environment input was not provided (i.e if the commit was pushed to main),
      # default to `development`. Effectively, the job below will run deploy for `development` on each push to main,
      # and use an input environment for manually triggered jobs
      CURRENT_ENVIRONMENT: ${{ github.event_name == 'push' && 'development' || inputs.environment }}

    # github currently does not support usage of env variables in job definitions
    name: Test ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    steps:
      # TODO: Currently we do not have a dev environment, so we cannot actually deploy.
      # Once dev is live -- remove the `if` conditions below.
      - name: Test variables
        id: test
        if:  ${{ env.CURRENT_ENVIRONMENT != 'development' }}
        run: echo "VARIABLE IS ${{vars.VARIABLE}}"
        continue-on-error: false
      - name: Test variables for development
        if: ${{ env.CURRENT_ENVIRONMENT == 'development' }}
        run: echo "JUST DEV. TODO"
      - name: Tag Deployment
        # Only run this step if the deployment succeeded.
        needs: [test]
        # if: test.result
        run: echo "RESULT IS ${{steps.test.result}}"

