name: Plan
on: push
# jobs:
#   test_dev:
#     uses: ./.github/workflows/test-base.yml
#     with:
#       environment: development
#     secrets: inherit
#   test_stg:
#     uses: ./.github/workflows/test-base.yml
#     with:
#       environment: staging
#     secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: dev
        uses: ./.github/workflows/test-base.yml
        with:
          environment: development
      - name: stg
        uses: ./.github/workflows/test-base.yml
        with:
          environment: staging