
name: "Test"
on:
  # This will trigger deployment to `development` on each push to main
  # `development` is set as a default environment below
  push:
    branches:
      - main
  # However, deployemnt to other environments (or re-running job for `development`) should be done manually
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true

# env:
#   # If the environment input was not provided (i.e if the commit was pushed to main),
#   # default to `development`. Effectively, the job below will run deploy for `development` on each push to main,
#   # and use an input environment for manually triggered jobs
#   CURRENT_ENVIRONMENT: ${{ github.event_name == 'push' && 'development' || inputs.environment }}

jobs:
  deploy:
    # github currently does not support usage of env variables on a job level definitions
    name: Test ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    # TODO: Currently we do not have a dev environment, so we cannot actually deploy.
    # Once dev is live -- remove the `if` condition below.
    # if: ${{ github.event_name != 'push' && inputs.environment != 'development' }}
    steps:
      - name: Test variables
        id: test
        run: echo "VARIABLE IS ${{vars.VARIABLE}}"
        continue-on-error: false

  tag-commit:
    permissions:
      contents: write
    name: Tag Commit
    runs-on: ubuntu-latest
    # Only run this step if the deployment succeeded.
    needs:
      - deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Tag Deployment
        shell: bash
        run: |
          set -x
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          CURRENT_COMMIT=$(git rev-parse HEAD)
          CURRENT_ENVIRONMENT="${{ github.event_name == 'push' && 'development' || inputs.environment }}"

          get_latest_tagged_commit() {
            local pattern=$1

            git for-each-ref --sort=-creatordate --format '(%objectname)' "refs/tags/$pattern" | head -n 1
          }

          get_commit_tags() {
            local commit=$1

            git tag -l --points-at $commit
          }

          LATEST_ENV_COMMIT=""

          for SEARCH_TAG in $(git tag -l | sort -r); do
            if [[ "$SEARCH_TAG" == "$CURRENT_ENV" || "$SEARCH_TAG" == *"-$CURRENT_ENV" ]]; then
              LATEST_ENV_COMMIT=$(git rev-parse $TAG^{commit} 2>/dev/null || echo "")
              if [ ! -z "$LATEST_ENV_COMMIT" ]; then
                break
              fi
            fi
          done

          CURRENT_TAGS=$(get_commit_tags $CURRENT_COMMIT)
          if [ ! -z "$CURRENT_TAGS" ]; then
            BASE_TAG=$(echo "$CURRENT_TAGS" | grep -v "$CURRENT_ENVIRONMENT" | head -n 1)
            if [ ! -z "$BASE_TAG" ]; then
              NEW_TAG="${BASE_TAG}-${CURRENT_ENVIRONMENT}"

              git tag -d "$BASE_TAG"
              git push --delete origin "$BASE_TAG" || true
            else
              NEW_TAG="$CURRENT_ENVIRONMENT"
            fi
          else
            NEW_TAG="$CURRENT_ENVIRONMENT"
          fi

          if [ ! -z "$LATEST_ENV_COMMIT" ] && [ "$LATEST_ENV_COMMIT" != "$CURRENT_COMMIT" ]; then
            PREV_TAGS=$(get_commit_tags $LATEST_ENV_COMMIT)
            for TAG in $PREV_TAGS; do
              if [[ "$TAG" == *"-CURRENT_ENVIRONMENT" ]]; then

                git tag -d "$TAG"
                git push --delete origin "$TAG" || true

                BASE_ENV=${TAG%-%CURRENT_ENV}
                if [ ! -z "$BASE_ENV" ]; then
                  git tag "$CURRENT_ENV" $LATEST_ENV_COMMIT
                  git push origin "$CURRENT_ENV"
                fi
              fi
            done
          fi

          echo "NEW TAG: $NEW_TAG"
          git tag "$NEW_TAG" $CURRENT_COMMIT
          git push origin "$NEW_TAG"

