name: Docker Build

on: push
    # paths:
    # identify paths
    # TODO: use output from glob?
    # - /outbound/integration-handlers/<partner>/<integration handler name>
jobs:
  init:
    runs-on: ubuntu-latest
    # outputs:
    #   to_build: ${{ steps.generate-matrix.outputs.to_build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Glob match
        uses: tj-actions/glob@v22
        id: glob
        with:
          files: /outbound/integration-handlers/**/Dockerfile

      - name: generate-matrix
        id: generate-matrix
        run: echo "${{ steps.glob.outputs.paths }}"