
name: "Test"
on:
  # This will trigger deployment to `development` on each push to main
  # `development` is set as a default environment below
  push:
    branches:
      - main
  # However, deployemnt to other environments (or re-running job for `development`) should be done manually
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true

env:
  # If the environment input was not provided (i.e if the commit was pushed to main),
  # default to `development`. Effectively, the job below will run deploy for `development` on each push to main,
  # and use an input environment for manually triggered jobs
  CURRENT_ENVIRONMENT: ${{ github.event_name == 'push' && 'development' || inputs.environment }}

jobs:
  variables:
    name: Test ${{ CURRENT_ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ CURRENT_ENVIRONMENT }}
    steps:
      # TODO: Currently we do not have a dev environment, so we cannot actually deploy.
      # Once dev is live -- remove the `if` conditions below.
      - name: Test variables
        id: test
        if:  ${{ env.CURRENT_ENVIRONMENT != 'development' }}
        run: echo "VARIABLE IS ${{vars.VARIABLE}}"
      - name: Test variables for development
        if: ${{ env.CURRENT_ENVIRONMENT == 'development' }}
        run: echo "JUST DEV. TODO"
      - name: Tag Deployment
        # Only run this step if the deployment succeeded.
        needs: [test]
        # if: test.result
        run: echo "RESULT IS ${{test.result}}"

